### ISSUE TITLE
Hinted version?

### ISSUE THREAD

**Issue by ortoslon** [CommercialType/RobotoSerif#8]
Will there be a hinted version of low-opsz instances at least? The Charter-esque simplification of details seems amenable to autohinting.

**Comment by mrecord** [comment]
There are no plans to build autohinted or manually hinted versions of the fonts. 
The fonts are built to Google's spec: unhinted fonts with minor adjustments to the GASP and PREP tables (using the [fix-nonhinting](https://github.com/googlefonts/gftools/blob/main/bin/gftools-fix-nonhinting.py) tool).

**Comment by Sunspark-007** [comment]
I find that postscript outlines tend to look better than truetype outlines. Are there any plans to make an otf version with postscript outlines?
