### ISSUE TITLE
Regressions since previous release

### ISSUE THREAD

**Issue by m4rc1e** [CommercialType/RobotoSerif#9]
"Z" and "z" have lost their anchors

<img width="73" alt="Screenshot 2023-02-07 at 13 38 34" src="https://user-images.githubusercontent.com/7525512/217260362-b77f3689-41a6-4194-ac21-b3ce6ee36070.png">

"h" as well

<img width="339" alt="Screenshot 2023-02-07 at 13 39 25" src="https://user-images.githubusercontent.com/7525512/217260487-eb29e46f-0bf1-4f74-a7cc-69fff0008ebf.png">

"gj" appear a bit too loose when compared against the current release

old: 
<img width="149" alt="Screenshot 2023-02-07 at 13 40 25" src="https://user-images.githubusercontent.com/7525512/217260809-c3975c5d-69ae-4e6f-85f5-7691189e0e22.png">

new:
<img width="151" alt="Screenshot 2023-02-07 at 13 40 55" src="https://user-images.githubusercontent.com/7525512/217260911-d4d092e9-d2f9-48c9-a952-764d1bf23d26.png">

All issues are present in both the Roman and Italic.

**Comment by m4rc1e** [comment]
The vertical metrics have also changed which is affecting Windows. Please reactivate fsSelection bit 7 and revert the OS/2 STypo values. The usWin vals should match the family's tallest yMin and yMax

**Comment by m4rc1e** [comment]
Marks below on "e" appear not as well placed in the Roman.

<img width="210" alt="Screenshot 2023-02-07 at 14 19 57" src="https://user-images.githubusercontent.com/7525512/217270272-a7119053-c3e1-4670-bd98-0e36b4aeab0e.png">

**Comment by davelab6** [comment]
All good requests :)

**Comment by mrecord** [comment]
updates:
- reapplied anchors, including new anchors for Cyrillic additions.
- adjusted gj kern pair
- fsSelection bit 7 turned on
- Applied unicodes: Tcedilla/tcedilla: 0163/0163, Tcommaaccent/tcommaaccent 021A/021B ([issue](https://github.com/googlefonts/roboto-serif/issues/12#issuecomment-1423230920))

**Comment by m4rc1e** [comment]
Thanks, I'll take a look tomorrow.
